services:
  main:
    container_name: API_Operaciones
    build: 
      context: ./API_Operaciones
      target: api
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - API_Operaciones/.env

  docs:
    container_name: API_Operaciones_Docs
    build: 
      context: ./API_Operaciones
      target: docs
    env_file:
      - API_Operaciones/.env

  nginx:
    build: ./API_Operaciones_WS
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - main
      - docs

volumes:
  static_volume: