# Generated by Django 5.0.10 on 2025-01-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenteuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='agenteuser',
            name='user_permissions',
        ),
    ]
