# Generated by Django 5.0.10 on 2025-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs_operaciones', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionesAPIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('api', models.CharField(max_length=255)),
                ('headers', models.JSONField()),
                ('body', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('client_ip_address', models.GenericIPAddressField()),
                ('response', models.TextField()),
                ('status_code', models.IntegerField()),
                ('execution_time', models.FloatField()),
                ('source_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'operaciones_api_log',
            },
        ),
    ]
