from rest_framework import serializers


class CalculoComisionRequestSerializer(serializers.Serializer):
    TIPO_INSTRUMENTO_CHOICES = [
        ("ACN", "Acciones Nacionales"),
        ("CFI", "Fondos Inversion"),
        ("ETN", "ETF Nacionales"),
    ]

    Tipo_Instrumento = serializers.ChoiceField(
        choices=TIPO_INSTRUMENTO_CHOICES, required=True
    )
    Rut_Cliente = serializers.CharField(required=True)
    Secuencia = serializers.IntegerField(required=True)


class CustodiaSerializer(serializers.Serializer):
    IdInterno = serializers.IntegerField()
    TipoFechaConsulta = serializers.CharField(max_length=255)
    FechaCustodia = serializers.DateField()
    IdClasificacionTipoInstrumento = serializers.CharField(max_length=255)
    NombreClasificacionTipoInstrumento = serializers.CharField(
        allow_null=True, required=False
    )
    IdTipoInstrumento = serializers.CharField(max_length=255)
    NombreTipoInstrumento = serializers.CharField(max_length=255)
    ISIN = serializers.CharField(max_length=255)
    IdInstrumento = serializers.IntegerField()
    NombreInstrumento = serializers.CharField(max_length=255)
    IdEmisor = serializers.CharField(max_length=255)
    EsFungible = serializers.CharField(max_length=1)
    IdPortafolio = serializers.IntegerField()
    DocumentoIdentidad = serializers.CharField(max_length=255)
    NombreCliente = serializers.CharField(max_length=255)
    CodigoPortafolio = serializers.CharField(max_length=255)
    IdBoveda = serializers.CharField(max_length=255)
    NumeroCuentaBoveda = serializers.CharField(allow_blank=True, required=False)
    Relacion = serializers.CharField(max_length=255)
    DescripcionRelacion = serializers.CharField(max_length=255)
    InteresCorridoCustodia = serializers.FloatField()
    IdMonedaPrincipal = serializers.CharField(max_length=3)
    CantidadCustodia = serializers.FloatField()
    PPPCustodia = serializers.FloatField()
    ValorPPPCustodia = serializers.FloatField()
    MontoPPPCustodia = serializers.FloatField()
    PrecioMercadoCustodia = serializers.FloatField()
    Rentabilidad = serializers.FloatField()
    ValorMercadoCustodia = serializers.FloatField()
    MontoMercadoCustodia = serializers.FloatField()
    DiferenciaMercadoCustodia = serializers.FloatField()
    IdMonedaReajuste = serializers.CharField(max_length=3)
    EsPagaderoEn = serializers.CharField(max_length=3)
    CantidadSimulCom = serializers.FloatField()
    PPPSimulCom = serializers.FloatField()
    ValorPPPSimulCom = serializers.FloatField()
    PrecioMercadoSimulCom = serializers.FloatField()
    ValorMercadoSimulCom = serializers.FloatField()
    DiferenciaMercadoSimulCom = serializers.FloatField()
    InteresCorridoSimulCom = serializers.FloatField()
    CantidadSimulVen = serializers.FloatField()
    PPPSimulVen = serializers.FloatField()
    ValorPPPSimulVen = serializers.FloatField()
    PrecioMercadoSimulVen = serializers.FloatField()
    ValorMercadoSimulVen = serializers.FloatField()
    DiferenciaMercadoSimulVen = serializers.FloatField()
    InteresCorridoSimulVen = serializers.FloatField()
    CantidadPrestamo = serializers.FloatField()
    PPPPrestamo = serializers.FloatField()
    ValorPPPPrestamo = serializers.FloatField()
    PrecioMercadoPrestamo = serializers.FloatField()
    ValorMercadoPrestamo = serializers.FloatField()
    InteresCorridoPrestamo = serializers.FloatField()
    CantidadEmpresti = serializers.FloatField()
    PPPEmpresti = serializers.FloatField()
    ValorPPPEmpresti = serializers.FloatField()
    PrecioMercadoEmpresti = serializers.FloatField()
    ValorMercadoEmpresti = serializers.FloatField()
    DiferenciaMercadoEmpresti = serializers.FloatField()
    InteresCorridoEmpresti = serializers.FloatField()
    CantidadGarantia = serializers.FloatField()
    PPPGarantia = serializers.FloatField()
    ValorPPPGarantia = serializers.FloatField()
    PrecioMercadoGarantia = serializers.FloatField()
    ValorMercadoGarantia = serializers.FloatField()
    DiferenciaMercadoGarantia = serializers.FloatField()
    InteresCorridoGarantia = serializers.FloatField()
    CantidadTransIng = serializers.FloatField()
    CantidadTransEgr = serializers.FloatField()
    TotalPosicion = serializers.FloatField()
    TotalPosicionPresunta = serializers.FloatField()
    FechaVencimiento = serializers.DateField()
    PrecioMonedaLocal = serializers.FloatField()
    PPPCustodiaLocal = serializers.FloatField()
    ValorMercadoCustodiaLocal = serializers.FloatField()
    ValorMercadoGarantiaLocal = serializers.FloatField()
    CantidadTransitoLocal = serializers.FloatField()
    MontoMercadoCustodiaLocal = serializers.FloatField()
    IdProductoAgrupador = serializers.IntegerField()
    CodigoTipoCuenta = serializers.CharField(max_length=255)
    TipoAhorro = serializers.CharField(max_length=255)
    TipoCuenta = serializers.CharField(max_length=255)
    Origen = serializers.CharField(max_length=255)
    IdRegimenTributario = serializers.CharField(max_length=255)
    IdMatrizAgrupador = serializers.IntegerField()
    EsADC = serializers.CharField(max_length=1)
    IdSerieFondo = serializers.CharField(max_length=255)


class SaldoSerializer(serializers.Serializer):
    IdCuentaInversion = serializers.IntegerField()
    CodigoCuentaInversion = serializers.CharField(max_length=50)
    IdCliente = serializers.IntegerField()
    IdPortafolio = serializers.IntegerField()
    FechaSaldo = serializers.DateField()
    IdMoneda = serializers.CharField(max_length=10)
    Saldo = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoDisponible = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoCargosPendientes = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoAbonosPendientes = serializers.DecimalField(max_digits=18, decimal_places=2)
    IdEjecutivo = serializers.IntegerField()
    NombreEjecutivo = serializers.CharField(max_length=100)
    CodigoSucursal = serializers.CharField(max_length=10)
    NombreSucursal = serializers.CharField(max_length=100)
    NombreCliente = serializers.CharField(max_length=100)
    DocumentoIdentidad = serializers.CharField(max_length=20)
    NombrePortafolio = serializers.CharField(max_length=100)
    PropositoPortafolio = serializers.CharField(max_length=50)
    CodigoPortafolio = serializers.CharField(max_length=10)
    CodigoMoneda = serializers.CharField(max_length=10)
    NombreMoneda = serializers.CharField(max_length=50)
    SaldoEnGarantia = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoAPlazoSimultanea = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoAPlazoVentaCorta = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoAPlazoCompromiso = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoRetiro = serializers.DecimalField(max_digits=18, decimal_places=2)
    SaldoRetenido = serializers.DecimalField(max_digits=18, decimal_places=2)
    Producto = serializers.CharField(max_length=100, required=False)
    IdProductoAgrupador = serializers.IntegerField()
    IdMatrizAgrupador = serializers.IntegerField()
    EsADC = serializers.CharField(max_length=1)
    MontoTransSolicitudesAporte = serializers.DecimalField(
        max_digits=18, decimal_places=2
    )
    TipoCambio = serializers.DecimalField(max_digits=18, decimal_places=2)


class MovimientoSerializer(serializers.Serializer):
    FechaEfectiva = serializers.DateField()
    FechaMovimiento = serializers.DateTimeField()
    Concepto = serializers.CharField()
    EsTransferencia = serializers.CharField()
    Moneda = serializers.CharField()
    Cargo = serializers.IntegerField()
    Abono = serializers.IntegerField()
    TipoComprobante = serializers.CharField()
    SecuenciaComprobante = serializers.CharField()
    FechaComprobante = serializers.DateTimeField()
    TipoProducto = serializers.CharField()
    TipoOperacion = serializers.CharField()
    FechaOperacion = serializers.DateTimeField()
    FechaVencimiento = serializers.DateField()
    SecuenciaOperacion = serializers.IntegerField()
    MontoOperacion = serializers.IntegerField()
    SecuenciaMovimiento = serializers.IntegerField()
    SecuenciaMovimientoTransferencia = serializers.IntegerField()
    NombreClienteRelacionado = serializers.CharField(allow_null=True)
    CodigoPortafolioRelacionado = serializers.CharField(allow_null=True)
    IngresadoPor = serializers.CharField()
    FechaDeCertificacion = serializers.DateTimeField()
    CertificadoPor = serializers.CharField(allow_blank=True)
    Descripcion = serializers.CharField(allow_blank=True)
    Estado = serializers.CharField()
    MotivoAnulacion = serializers.CharField(allow_blank=True)
    Autorizacion = serializers.CharField(allow_blank=True)
    EstadoAutorizacion = serializers.CharField(allow_blank=True)
    FechaLiquidacion = serializers.DateField()
    FolioComprobante = serializers.CharField()
    Cantidad = serializers.IntegerField()
    Saldo = serializers.IntegerField()
    IdInstrumento = serializers.IntegerField()
    NombreCliente = serializers.CharField()
    IdCliente = serializers.IntegerField()
    IdPortafolio = serializers.IntegerField()
    IdConcepto = serializers.CharField()
    IdEstado = serializers.CharField()
    NombreTipoMovimiento = serializers.CharField()
    SaldoSimulado = serializers.IntegerField()
    CodigoPortafolio = serializers.CharField()
    IdComprobante = serializers.IntegerField()
    IdRespuestaDTE = serializers.IntegerField()
    RespuestaPdfDTE = serializers.CharField(allow_blank=True)
    DocumentoIdentidad = serializers.CharField()
    Origen = serializers.CharField()
    IdMatrizAgrupador = serializers.IntegerField()
    NemotecnicoOriginal = serializers.CharField()
    EsADC = serializers.CharField()


class ClienteSerializer(serializers.Serializer):
    nombre_cliente = serializers.CharField()
    apellido_cliente = serializers.CharField()
    razon_social_cliente = serializers.CharField()
    documento_cliente = serializers.CharField()
    rut_cliente = serializers.CharField()
    nombre_agente = serializers.CharField()
    apellido_agente = serializers.CharField()
    razon_social_agente = serializers.CharField()
